#!/usr/bin/with-contenv ash

echo "Starting openvpn"

exec openvpn --reneg-sec 0 --mute-replay-warnings --auth-nocache --script-security 2 --up-delay --up-restart --writepid /config/openvpn.pid --remap-usr1 SIGHUP --pull-filter ignore 'up' --pull-filter ignore 'down' --remote-random --verb 6 --config /etc/openvpn/slickvpn/United-States-Columbus.ovpn
