#!/usr/bin/with-contenv bash

VPN_ENABLED=${VPN_ENABLED:-no}
VPN_ENABLED=`echo ${VPN_ENABLED} | tr [:upper:] [:lower:]`
VPNCONFIG=${VPNCONFIG:-TorGuard.USA-NEW-YORK}

VPNPID="/config/openvpn.pid"
VPNCONFIGPATH="/etc/openvpn"
VPNOPTIONS="--writepid ${VPNPID} --verb 1 --script-security 2 --up /etc/openvpn/vpnup.sh --down /etc/openvpn/vpndown.sh"

cat /dev/null > /config/.startingenv
for e in `env`; do
 echo "Saving ${e}"
 echo "export ${e}" >>/config/.startingenv
done

if [ ! -c /dev/net/tun ]; then
  if [ ! -d /dev/net ]; then
    echo "Making /dev/net"
    mkdir -p /dev/net
  fi
  echo "Making node /dev/net/tun"
  mknod /dev/net/tun c 10 200
  chmod 0666 /dev/net/tun
fi

if [ "${VPN_ENABLED}" != "no" ]; then
  echo "Starting openvpn"
  exec openvpn ${VPNOPTIONS} --config ${VPNCONFIGPATH}/${VPNCONFIG}.ovpn --auth-user-pass /config/openvpn-credentials.txt
fi
