#!/usr/bin/with-contenv bash

GW=`ip r | grep default|awk '{print $3}'`
if [ ! -z "${LAN_NETWORK}" ]; then
  IFS=','; tokens=( ${LAN_NETWORK} )
  for subnet in "${tokens[@]}"; do
    echo "Adding static route for ${subnet} ${GW}"
    route add ${subnet} gw ${GW}
  done
fi
